============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-7.4.4, pluggy-1.4.0
cachedir: /home/jinhyuk2me/dev_ws/Shopee/ros2_ws/build/shopee_main_service/.pytest_cache
rootdir: /home/jinhyuk2me/dev_ws/Shopee/ros2_ws/src/shopee_main_service
plugins: launch-testing-ros-0.26.9, ament-lint-0.17.3, ament-flake8-0.17.3, ament-xmllint-0.17.3, launch-testing-3.4.6, ament-pep257-0.17.3, launch-pytest-3.4.6, ament-copyright-0.17.3, mock-3.12.0, timeout-2.2.0, anyio-4.2.0, colcon-core-0.20.0, cov-4.1.0, rerunfailures-12.0, None-None, typeguard-4.1.5
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/lib/python3/dist-packages/pluggy/_hooks.py:501: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
/usr/lib/python3/dist-packages/pluggy/_manager.py:119: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/lib/python3/dist-packages/_pytest/python.py:215: in pytest_collect_file
    module: Module = ihook.pytest_pycollect_makemodule(
/usr/lib/python3/dist-packages/_pytest/config/compat.py:66: in fixed_hook
    return hook(**kw)
/usr/lib/python3/dist-packages/pluggy/_hooks.py:501: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
/usr/lib/python3/dist-packages/pluggy/_manager.py:119: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/opt/ros/jazzy/lib/python3.12/site-packages/launch_testing/pytest/hooks.py:193: in pytest_pycollect_makemodule
    entrypoint = find_launch_test_entrypoint(path)
/opt/ros/jazzy/lib/python3.12/site-packages/launch_testing/pytest/hooks.py:183: in find_launch_test_entrypoint
    module = import_path(path, root=None)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:995: in exec_module
    ???
<frozen importlib._bootstrap>:488: in _call_with_frames_removed
    ???
shopee_main_service/__init__.py:4: in <module>
    from .config import MainServiceConfig
shopee_main_service/config.py:13: in <module>
    from pydantic_settings import BaseSettings, SettingsConfigDict
E   ModuleNotFoundError: No module named 'pydantic_settings'
- generated xml file: /home/jinhyuk2me/dev_ws/Shopee/ros2_ws/build/shopee_main_service/pytest.xml -
=========================== short test summary info ============================
ERROR  - ModuleNotFoundError: No module named 'pydantic_settings'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.12s ===============================
